### ISSUE TITLE
Webhook Connectors being Deprecated 10/1/2024

### ISSUE THREAD

**Issue by memoriesnate** [wellbia/redmine_microsoftteams#9]
Microsoft is deprecating the Teams webhook connectors and a webhooks will need to be sent to Power Automate to send a notification to a Teams channel.

Currently the json that is sent from the plugin fails when sending it to the new Power Automate webhook urls.

Action 'Send_each_adaptive_card' failed: The execution of template action 'Send_each_adaptive_card' failed: the result of the evaluation of 'foreach' expression '@triggerOutputs()?['body']?['attachments']' is of type 'Null'. The result must be a valid array.

**Comment by hgyoon-w** [comment]
This support was added at https://github.com/wellbia/redmine_microsoftteams/commit/257f1e5210d381d07e99b384587e902d601fffb3
